class Locators:
    USER_NAME_LOCATOR = "//*[@class='_2IX_2- VJZDxU']"
    PASSWORD_LOCATOR = "//*[@class='_2IX_2- _3mctLh VJZDxU']"
    LOGIN_BUTTON_LOCATOR ="//*[@class='_2KpZ6l _2HKlqd _3AWRsL']"
    POPUP = "//button[@class='_2KpZ6l _2doB4z']"
    LOGIN = "//*[@class='_1_3w1N']"
    SEARCH = "//input[@class='_3704LK']"
    BUY_NOW ="//button[.=' BUY NOW']"
    IPHONE_LOCATOR = "//div[.='APPLE iPhone 13 (Midnight, 256 GB)']"
    ADD_NEW_ADDRESS_LOCATOR = "//div[text()='Add a new address']"

    NAME_LOCATOR = "//input[@name='name']"
    PHONE_LOCATOR = "//input[@name='phone']"
    PINCODE_LOCATOR = "//input[@name='pincode']"
    LOCALITY_LOCATOR ="//input[@name='addressLine2']"
    ADDRESS_LOCATOR = "//textarea[@name='addressLine1']"
    STATE_LOCATOR = "//select[@name='state']"
    DELIVERY_TIME_LOCATOR = "//*[text()='Work (Delivery between 10 AM - 5 PM)']"
    PLACE_ORDER_LOCATOR = "//*[.='Save and Deliver Here']"