class TestData:
    USER_NAME = "9340952682"
    PASSWORD  = "demopass"
    URL = "https://www.flipkart.com"
    PRODUCT = "i phone 13"
    NAME = "AAMIR"
    PHONE ="9999999999"
    LOCALITY = "PUNE"
    PINCODE = "672182"
    STATE = "Maharashtra"
    ADDRESS = "NEOVA SOLUTIONS PVT LTD"